# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: run bobot

env:
  SERVER: production
#defaults:
#  run:
#    working-directory: ../
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "50 0 * * *" #UTC Time (减8)
    
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
    - name: Startup and first login
      #export WECHATY_LOG=verbose
      run: |
        node main.js
        ls *.memory-card.json
        cat jadetreer.memory-card.json
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
    - name: Upload memory-card
      uses: actions/upload-artifact@v2
      with:
        name: memory-card
        path: |
          *.memory-card.json

  run_1st:
    name: run bobot 1st
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
    - name: Download memory-card for bobot
      uses: actions/download-artifact@v2
      with:
        name: memory-card
    - name: Startup
      #export WECHATY_LOG=verbose
      run: |
        ls
        node main.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  run_2nd:
    name: run bobot 2nd
    needs: [build,run_1st]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
    - name: Download memory-card for bobot
      uses: actions/download-artifact@v2
      with:
        name: memory-card
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node main.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  run_3rd:
    name: run bobot 3rd
    needs: [build,run_2nd]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
    - name: Download memory-card for bobot
      uses: actions/download-artifact@v2
      with:
        name: memory-card
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node main.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  run_4th:
    name: run bobot 4th
    needs: [build,run_3rd]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
    - name: Download memory-card for bobot
      uses: actions/download-artifact@v2
      with:
        name: memory-card
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node main.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
