# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: run bobot

env:
  SERVER: production
defaults:
  run:
    working-directory: ../
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "50 0 * * *" #UTC Time (减8)
    
jobs:
  build:
    name: build bobot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        cd bobot
        npm i wechaty-puppet-puppeteer
        npm i
    - name: Upload artifact for bobot
      uses: actions/upload-artifact@v2
      with:
        name: bobot
        path: bobot

  run_1st:
    name: run bobot 1st
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - name: Download artifact for bobot
      uses: actions/download-artifact@v2
      with:
        name: bobot
    - name: Startup
      #export WECHATY_LOG=verbose
      run: |
        pwd
        ls
        node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  run_2nd:
    name: run bobot 2nd
    needs: [build,run_1st]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - name: Cache bobot workspace
      uses: actions/cache@v2
      env:
        cache-name: cache-bobot
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  run_3rd:
    name: run bobot 3rd
    needs: [build,run_2nd]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - name: Cache bobot workspace
      uses: actions/cache@v2
      env:
        cache-name: cache-bobot
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  run_4th:
    name: run bobot 4th
    needs: [build,run_3rd]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - name: Cache bobot workspace
      uses: actions/cache@v2
      env:
        cache-name: cache-bobot
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
