# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "50 0 * * *" #UTC Time (减8)
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i wechaty-puppet-puppeteer
        npm i
        
  Startup 1st:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  Startup 2nd:
    runs-on: ubuntu-latest
    needs: Startup 1st
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  Startup 3rd:
    runs-on: ubuntu-latest
    needs: Startup 2nd
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
  Startup 4th:
    runs-on: ubuntu-latest
    needs: Startup 3rd
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
