# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "50 0/6 * * *" #UTC Time (减8)
    
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 1440

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i wechaty-puppet-puppeteer
        npm i
    - name: Startup
      #export WECHATY_LOG=verbose
      run: node bobot.js
      env:
          WXCOM_BOT_KEY: ${{ secrets.WXCOM_BOT_KEY }}
